image: node

stages:
  - install
  - build
  - pages

tw:
  stage: install
  script:
    - npm install -g tiddlywiki

i18n:
  stage: build
  script:
    - git checkout i18n
    - git pull
    - cp -R * /usr/local/lib/node_modules/tiddlywiki/
    - tiddlywiki ./editions/i18n --build
    - mv ./editions/output public
  stage: pages
  artifacts:
    name: "TEST_%CI_PIPELINE_ID%"
    when: on_success
    paths:
      - 'public/i18n.html'
  only:
    - i18n
    - master
    - release

collection:
  stage: build
  script:
    - git checkout release
    - git pull
    - cp -R * /usr/local/lib/node_modules/tiddlywiki/
    - tiddlywiki ./editions/collection --build
    - mv ./editions/output public
    - cp -R ./files/* public
  stage: pages
  artifacts:
    paths:
      - public
  only:
    - release
