image: node

stages:
  - test
  - build
  - pages

collection:
  stage: build
  script:
    - git checkout release
    - git pull
    - npm install -g tiddlywiki
    - cp -R * /usr/local/lib/node_modules/tiddlywiki/
    - tiddlywiki ./editions/collection --build
    - tiddlywiki ./editions/i18n --build
    - mkdir .public
    - mv ./editions/output/dev/* ./editions/output
    - mv ./editions/output/* .public
    - mv .public public
    - cp -R ./files/* public
  stage: pages
  artifacts:
    paths:
      - public
  only:
    - release

i18n:
  stage: test
  script:
    - ls public
  stage: build
  script:
    - git checkout i18n
    - git pull
    - npm install -g tiddlywiki
    - cp -R * /usr/local/lib/node_modules/tiddlywiki/
    - tiddlywiki ./editions/i18n --build
  stage: pages
  script:
    - mkdir .public
    - mv ./editions/output/dev .public
    - ls -al .public/
    - cp -R .public public
    - ls -al public/
    artifacts:
      paths:
        - public
  only:
    - i18n
    - release
