image: node

pages:
  script:
  - npm install -g tiddlywiki
  - tiddlywiki ./editions/collection --build
  - mv ./editions/collection/output public
  artifacts:
    paths:
    - public
  only:
  - master
