image: node

pages:
  script:
# collection
  - git checkout release
  - git pull
  - npm install -g tiddlywiki
  - cp -R * /usr/local/lib/node_modules/tiddlywiki/
  - tiddlywiki ./editions/collection --build
  - tiddlywiki ./editions/i18n --build
  - mkdir .public
  - mv ./editions/output/dev/* ./editions/output
  - mv ./editions/output/* .public
  - mv .public public
  - cp -R ./files/* public
# i18n (possibly use branch name?)
  - git checkout i18n
  - git pull
  - npm install -g tiddlywiki
  - cp -r * /usr/local/lib/node_modules/tiddlywiki/
  - tiddlywiki ./editions/i18n --build
  - cp ./editions/output/dev .public
# another branch...
# ...
  - cp -r .public public
  artifacts:
    paths:
    - public
