image: node

pages:
  script:
  - npm install -g tiddlywiki
  - cp -R * /usr/local/lib/node_modules/tiddlywiki/
  - tiddlywiki ./editions/collection --build
  - tiddlywiki ./editions/tree-macro --build
  - gzip --recursive --keep ./editions/*/output
  - mv ./editions/*/output public
  - cp -R ./files/* public
  artifacts:
    paths:
    - public
  only:
  - release
  - master
