image: node

# collection
pages:
  script:
  - git checkout release
  - git pull
  - npm install -g tiddlywiki
  - cp -R * /usr/local/lib/node_modules/tiddlywiki/
  - tiddlywiki ./editions/collection --build
  - tiddlywiki ./editions/i18n --build
  - mkdir .public
  - mv ./editions/output/dev/* ./editions/output
  - mv ./editions/output/* .public
  - mv .public public
  - cp -R ./files/* public
  artifacts:
    paths:
    - public

# i18n (possibly use branch name?)
pages:
  script:
# testings
  - git checkout i18n
  - git pull
  - npm install -g tiddlywiki
  - cp -r * /usr/local/lib/node_modules/tiddlywiki/
  - tiddlywiki ./editions/i18n --build
  - mkdir .public
  - mv ./editions/output/dev .public
  - cp -r .public public
  artifacts:
    paths:
    - public
  only:
  - i18n
