image: node

pages:
  script:
# collection
  - git config --global user.email "bot@bot-for-this-project.me"
  - git config --global user.name "A Bot"
  - git checkout release
  - git pull
  - npm install -g tiddlywiki
  - cp -R * /usr/local/lib/node_modules/tiddlywiki/
  - tiddlywiki ./editions/collection --build
#  - tiddlywiki ./editions/i18n --build
  - mkdir .public
# à activer quand j'aurai mergé  - cp ./editions/output/dev/* ./editions/output
  - mv ./editions/collection/output/* .public
  - git add .public/*
  - git stash
  # i18n (possibly use branch name?)
  - git checkout i18n
  - git pull
  - git stash pop
  - npm install -g tiddlywiki
  - cp -r * /usr/local/lib/node_modules/tiddlywiki/
  - tiddlywiki ./editions/i18n --build
  - cp ./editions/output/dev .public
#  - git add .public/*
#  - git stash
# another branch...
# ...
  - mv .public public
  - cp -R ./files/* public
  artifacts:
    paths:
    - public
