image: node

pages:
  script:
  - npm install -g tiddlywiki
  - cp -R * /usr/local/lib/node_modules/tiddlywiki/
  - tiddlywiki ./editions/collection --build
  - mv ./editions/collection/output public
  - cp -R ./files/* public
  artifacts:
    paths:
    - public
  only:
  - master
