image: node

stages:
  - build
  - pages

collection:
  stage: build
  script:
    - git checkout release
    - git pull
    - npm install -g tiddlywiki
    - cp -R * /usr/local/lib/node_modules/tiddlywiki/
    - tiddlywiki ./editions/collection --build
    - tiddlywiki ./editions/i18n --build
    - mv ./editions/output/dev/* ./editions/output
    - mv ./editions/output public
    - cp -R ./files/* public
  stage: pages
  artifacts:
    paths:
      - public
  only:
    - release

i18n:
  stage: build
  script:
    - git checkout i18n
    - git pull
    - npm install -g tiddlywiki
    - cp -R * /usr/local/lib/node_modules/tiddlywiki/
    - tiddlywiki ./editions/i18n --build
    - mv ./editions/output public
  stage: pages
  artifacts:
    name: "TEST_%CI_PIPELINE_ID%"
    when: on_success
    paths:
      - 'public/dev/i18n.html'
  only:
    - i18n
    - release
