image: node

pages:
  script:
  - npm install -g tiddlywiki
  - cp -R * /usr/local/lib/node_modules/tiddlywiki/
  - tiddlywiki ./editions/collection --build
  - mv ./editions/collection/output public
  - cp -R ./files/* public
  artifacts:
    paths:
    - public
  only:
  - release

pages:
  script:
    - wget "https://sycom.gitlab.io/"
    - npm install -g tiddlywiki
    - cp -R * /usr/local/lib/node_modules/tiddlywiki/
    - tiddlywiki ./editions/collection --build
    - mkdir -p public/dev
    - mv ./editions/collection/output public/dev
    - cp -R ./files/* public/dev
    - tiddlywiki ./editions/atom-feed --build
    - mkdir -p public/atom-feed
    - mv ./editions/atom-feed/output public/atom-feed
    - cp -R .public/* public
  artifacts:
    paths:
    - public
  only:
  - master
